repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: fix-style
        name: fix style
        entry: scripts/fix-style
        language: system
        require_serial: true
        types: [python]
        include: ^backend/
  - repo: local
    hooks:
      - id: check-types
        name: check types
        entry: scripts/check-types
        language: system
        require_serial: true
        types: [python]
        include: ^backend/
