services:
  django:
    build:
      context: backend
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - PID_SERVICE_URL=http://pid-service.test
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=instrumentdb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=supersecret
      - SECRET_KEY=donutsteel
      - PUBLIC_URL=http://localhost:8000
      - MODE=development
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./database:/docker-entrypoint-initdb.d
