services:
  django:
    build:
      context: backend
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - PID_SERVICE_URL=
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=cfs
      - DATABASE_USER=AzureDiamond
      - DATABASE_PASSWORD=hunter2
      - DATABASE_SERVICE=database
      - DATABASE_SERVICE_HOST=database
      - DATABASE_SERVICE_PORT=5432
      - SECRET_KEY=donutsteel
      - DEBUG=1
      - PUBLIC_URL=http://localhost:8000
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: AzureDiamond
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: cfs
