# Generated by Django 4.2.8 on 2023-12-20 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"verbose_name_plural": "log entries"},
        ),
    ]
