# Generated by Django 4.2.7 on 2024-02-15 09:12

import datetime

from django.db import migrations, models


def set_dates(apps, schema_editor):
    LogEntry = apps.get_model("logbook", "logentry")
    for log_entry in LogEntry.objects.all():
        log_entry.date = log_entry.created_at.date()
        log_entry.save()


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0002_alter_logentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(set_dates, migrations.RunPython.noop),
    ]
