# Generated by Django 4.0.2 on 2022-02-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name by which the instrument instance is known.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Technical description of the device and its capabilities.",
                    ),
                ),
                ("commission_date", models.DateField(blank=True, null=True)),
                ("decommission_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ror_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("ARK", "ARK"),
                            ("arXiv", "arXiv"),
                            ("bibcode", "bibcode"),
                            ("DOI", "DOI"),
                            ("EAN13", "EAN13"),
                            ("EISSN", "EISSN"),
                            ("Handle", "Handle"),
                            ("IGSN", "IGSN"),
                            ("ISBN", "ISBN"),
                            ("ISSN", "ISSN"),
                            ("ISTC", "ISTC"),
                            ("LISSN", "LISSN"),
                            ("PMID", "PMID"),
                            ("PURL", "PURL"),
                            ("RAiD", "RAiD"),
                            ("RRID", "RRID"),
                            ("UPC", "UPC"),
                            ("URL", "URL"),
                            ("URN", "URN"),
                            ("w3id", "w3id"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("IsDescribedBy", "Described by"),
                            ("IsNewVersionOf", "New version of"),
                            ("IsPreviousVersionOf", "Previous version of"),
                            ("HasComponent", "Has component"),
                            ("IsComponentOf", "Component of"),
                            ("References", "References"),
                            ("HasMetadata", "Has metadata"),
                            ("WasUsedIn", "Was used in"),
                            ("IsIdenticalTo", "Identical to"),
                            ("IsAttachedTo", "Attached to"),
                        ],
                        max_length=19,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_identifiers",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "manufacturers",
                    models.ManyToManyField(to="instruments.Organization"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instrument",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="instruments.model"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="owners",
            field=models.ManyToManyField(to="instruments.Organization"),
        ),
        migrations.AddField(
            model_name="instrument",
            name="types",
            field=models.ManyToManyField(
                help_text="Classification of the type of the instrument.",
                to="instruments.Type",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="variables",
            field=models.ManyToManyField(
                help_text="The variable(s) that this instrument measures or observes.",
                to="instruments.Variable",
            ),
        ),
        migrations.CreateModel(
            name="AlternateIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("SerialNumber", "Serial number"),
                            ("InventoryNumber", "Inventory number"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_identifiers",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
    ]
