# Generated by Django 4.0.2 on 2022-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='Classification of the type of the instrument.', null=True, to='instruments.Type'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='variables',
            field=models.ManyToManyField(blank=True, help_text='The variable(s) that this instrument measures or observes.', null=True, to='instruments.Variable'),
        ),
    ]
