# Generated by Django 4.0.2 on 2022-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instrument_types_alter_instrument_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
