# Generated by Django 4.0.2 on 2022-02-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0005_person_instrument_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.person",
            ),
        ),
    ]
