# Generated by Django 4.0.2 on 2022-02-14 12:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0007_alter_person_orcid_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
