# Generated by Django 4.0.2 on 2022-02-16 15:20

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0009_alter_instrument_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
