# Generated by Django 4.0.2 on 2022-04-14 07:50

import instruments.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0010_alter_instrument_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ror_id",
            field=instruments.fields.RorIdField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="orcid_id",
            field=instruments.fields.OrcidIdField(blank=True, max_length=19, null=True),
        ),
    ]
