# Generated by Django 4.0.2 on 2022-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0013_alter_organization_ror_id_alter_person_orcid_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="types",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="variables",
        ),
        migrations.AddField(
            model_name="model",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classification of the type of the instrument.",
                to="instruments.Type",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="variables",
            field=models.ManyToManyField(
                blank=True,
                help_text="The variable(s) that this instrument measures or observes.",
                to="instruments.Variable",
            ),
        ),
    ]
