# Generated by Django 4.0.2 on 2022-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "instruments",
            "0014_remove_instrument_types_remove_instrument_variables_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="pid",
            field=models.URLField(null=True, unique=True),
        ),
    ]
