# Generated by Django 4.0.2 on 2022-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0015_instrument_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="pid",
            field=models.URLField(null=True, unique=True, verbose_name="PID"),
        ),
    ]
