# Generated by Django 4.0.4 on 2022-05-24 11:49

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0017_instrument_serial_number_delete_alternateidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
