# Generated by Django 4.0.5 on 2022-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0019_alter_instrument_image_alter_model_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="acronym",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
