# Generated by Django 4.1 on 2022-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0020_organization_acronym"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="concept_url",
            field=models.URLField(blank=True, null=True, verbose_name="Concept URL"),
        ),
        migrations.AddField(
            model_name="type",
            name="concept_url",
            field=models.URLField(blank=True, null=True, verbose_name="Concept URL"),
        ),
        migrations.AddField(
            model_name="variable",
            name="concept_url",
            field=models.URLField(blank=True, null=True, verbose_name="Concept URL"),
        ),
    ]
