# Generated by Django 4.1 on 2022-09-01 11:04

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


def migrate_dates(apps, schema_editor):
    Instrument = apps.get_model("instruments", "Instrument")
    Campaign = apps.get_model("instruments", "Campaign")
    for instrument in Instrument.objects.all():
        Campaign.objects.create(
            instrument=instrument,
            date_range=(instrument.commission_date, instrument.decommission_date),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0021_model_concept_url_type_concept_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_range", django.contrib.postgres.fields.ranges.DateRangeField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="instruments.instrument",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="instruments.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="instrument",
            name="locations",
            field=models.ManyToManyField(
                through="instruments.Campaign", to="instruments.location"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("date_range", "&&"), ("instrument_id", "=")],
                name="exclude_overlapping_campaigns",
                violation_error_message="Overlaps with another campaign.",  # type: ignore
            ),
        ),
        migrations.RunPython(migrate_dates),
        migrations.RemoveField(
            model_name="instrument",
            name="commission_date",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="decommission_date",
        ),
    ]
