# Generated by Django 4.1 on 2022-10-28 09:57

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


def migrate_contacts(apps, schema_editor):
    Instrument = apps.get_model("instruments", "Instrument")
    Pi = apps.get_model("instruments", "Pi")
    for inst in Instrument.objects.all():
        Pi.objects.create(
            instrument=inst, person=inst.contact_person, date_range=(None, None)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0023_remove_campaign_exclude_overlapping_campaigns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_range", django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.AddField(
            model_name="instrument",
            name="persons",
            field=models.ManyToManyField(
                through="instruments.Pi", to="instruments.person"
            ),
        ),
        migrations.AddField(
            model_name="pi",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="instruments.instrument"
            ),
        ),
        migrations.AddField(
            model_name="pi",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.person",
            ),
        ),
        migrations.RunPython(migrate_contacts),
        migrations.RemoveField(
            model_name="instrument",
            name="contact_person",
        ),
    ]
