# Generated by Django 4.1 on 2022-10-31 11:00

from typing import List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0024_pi_remove_instrument_contact_person_and_more"),
    ]

    operations: List = []
