# Generated by Django 4.1 on 2022-10-31 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0024_pi_remove_instrument_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="instruments.location"
            ),
        ),
        migrations.AlterField(
            model_name="pi",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="instruments.person"
            ),
        ),
    ]
