# Generated by Django 4.1 on 2022-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0025_alter_campaign_location_alter_pi_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
