# Generated by Django 4.1 on 2022-10-31 11:02

from django.db import migrations


def split_names(apps, schema_editor):
    Person = apps.get_model("instruments", "Person")
    for person in Person.objects.all():
        person.first_name, person.last_name = person.full_name.split(maxsplit=1)
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0026_person_first_name_person_last_name"),
    ]

    operations = [
        migrations.RunPython(split_names),
    ]
