# Generated by Django 4.1 on 2022-10-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0027_person_split_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="full_name",
        ),
    ]
