# Generated by Django 4.1.2 on 2022-11-10 15:30

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0029_alter_pi_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="instruments.location"
            ),
        ),
        migrations.AlterField(
            model_name="pi",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True),
        ),
    ]
