# Generated by Django 4.1.7 on 2023-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0031_instrument_components_alter_instrument_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="components",
            field=models.ManyToManyField(
                blank=True, related_name="component_of", to="instruments.instrument"
            ),
        ),
    ]
