# Generated by Django 4.1.7 on 2023-03-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0034_instrument_image_attribution_model_image_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="new_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="instruments.instrument",
            ),
        ),
    ]
