# Generated by Django 4.2.7 on 2024-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0039_rename_pi_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="role",
            field=models.TextField(
                choices=[("pi", "Principal investigator"), ("extra", "Extra person")],
                default="pi",
            ),
            preserve_default=False,
        ),
    ]
